# -*- coding: utf-8 -*-
"""Embeddings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gEirQt1NZ-LwDW4ioU-DU0iDod1T9b-l

# Processamento de Linguagem Natural

## Embeddings - Prática

# 1- Usando Word embeddings pré-treinadas

Algumas opções de word embeddings pré-treinadas para o portugues são:


*   Word embeddings monolíngues (ex: NILC word embeddings - disponíveis em http://nilc.icmc.usp.br/embeddings)
*   Word embeddings multilíngues (ex: MUSE word embeddings - disponíveis em http://github.com/facebookresearch/MUSE)

Foram escolhidas as word embeddings do NILC treinadas com GloVe conforme informações disponíveis na página do NILC word embeddings citada acima.
"""

!pip install torch pot gensim transformers # depois de rodar a 1 vez, pode comentar essa linha

!wget https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.pt.300.vec.gz -O cc.pt.300.vec.gz

!gunzip cc.pt.300.vec.gz

import gensim

nilc_glove = gensim.models.KeyedVectors.load_word2vec_format("cc.pt.300.vec")

nilc_glove["rainha"]

nilc_glove.similarity("rei", "rainha").item()

"""# Verificando a similaridade entre palavras

Nesta seção faremos algumas manipulações básicas com as WEs do NILC para encontrar a similaridade entre palavras.
Por exemplo, a operação abaixo

resultado = vetor[mulher] + vetor[rei] - vetor[homem]

o vetor mais próximo do resultado é o vetor de "rainha".
"""

resultado = nilc_glove.most_similar(positive=["mulher", "rei"], negative=["homem"], topn=5)

for palavra, score in resultado:
    print(f"{palavra} : {score:.4f}")

resultado2 = nilc_glove.most_similar(positive=['amar', 'odiando'], negative=['odiar'], topn=5)

for palavra, score in resultado2:
    print(f"{palavra} : {score:.4f}")

"""Também podemos conferir quais são as n palavras mais próximas (o default do most_similar é n=10) de uma determinada palavra, por exemplo: "escola"."""

nilc_glove.most_similar("escola")

"""também é possível calcular o valor de similaridade (usando cosseno, por default) entre duas palavras."""

print("Similaridade entre menino e menina: ", nilc_glove.similarity("menino", "menina"))

"""E verificar qual palavra distoa em um grupo de quatro palavras, por exemplo: menina, menino, cão e garota."""

print(nilc_glove.doesnt_match("menina menino cão garota".split()))

"""# Verificando a similaridade entre sentenças

Além de verificar a similaridade entre palavras, o gensim disponibiliza algumas rotinas para calcular a similaridade entre as sentenças. Por exemplo, a similaridade da sentença "O menino foi para a escola de ônibus". e as sentenças "Ana foi para a escola ontem". e "A menina foi para casa". Veja que a similaridade com a última é maior do que com a primeira.
"""

sentenca = "O menino foi para a escola de ônibus".lower().split()

sent1 = "Ana foi para a escola ontem".lower().split()
similaridade = nilc_glove.wmdistance(sentenca, sent1)
print("{:.4f}".format(similaridade))

sent2 = "A menina foi para casa".lower().split()
similaridade = nilc_glove.wmdistance(sentenca, sent2)
print("{:.4f}".format(similaridade))

"""# BERTimbau

Modelo de linguagem contextualizado para o portugues
"""

import torch
from transformers import BertTokenizer
from transformers import BertForPreTraining
from transformers import BertModel

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

tokenizer = BertTokenizer.from_pretrained('neuralmind/bert-large-portuguese-cased', do_lower_case=False)
bert = BertModel.from_pretrained('neuralmind/bert-large-portuguese-cased').to(device)

texto = "Eu vou ao banco pagar a conta hoje."

# Tokenizando o texto
input_ids = tokenizer.encode(texto, return_tensors='pt')
wordpieces = tokenizer.convert_ids_to_tokens(input_ids[0])

# salvando ponteiros para palavras
subwords_idx = []
for i, wordpiece in enumerate(wordpieces):
  if '##' not in wordpiece and i not in [0, len(wordpieces)-1]:
    subwords_idx.append(i)

# Obtendo os vetores para as palavras
input_ids = input_ids.to(device)
with torch.no_grad():
  outs = bert(input_ids)
  vetores = outs[0][0, :]

print(vetores[subwords_idx].size(), '\n')
vetores[subwords_idx]

"""# Gerando sua próprias word embeddings

Agora vamos gerar WEs para um corpus. Veja que todas as rotinas e os cálculos apresentados anteriormente continuam aplicáveis com as novas WEs

# O Corpus

Utilizando os dados de um desafio do Kaggle para análise de sentimentos, em portugues

https://www.kaggle.com/augustop/portuguese-tweets-for-sentiment-analysis
"""

!wget https://www.dropbox.com/s/bdr4tmkxcvk9pqc/NothemeTweets.csv.zip?dl=1 -O NothemeTweets.csv.zip
!unzip -o NothemeTweets.csv.zip

"""Usando o pandas para visualizar os campos do arquivo .csv"""

import pandas as pd
corpus = pd.read_csv("NoThemeTweets.csv", sep=',')
corpus.head(10)

"""Vamos utilizar somente o campo tweet_text, que contém os tweets, nosso objeto de interesse. Por exemplo, o terceiro tweet é acessado na posição 2 (as posições começam no 0)"""

tweets = corpus["tweet_text"].values
tweets[2]

"""# Processamento Básico

Neste processamento, utilizaremos a biblioteca NLTK
"""

import nltk
nltk.download('punkt')
nltk.download('stopwords')
stopwords = nltk.corpus.stopwords.words('portuguese')

"""Primeiro, vamos "ler" e armazenar todas as sentenças (tweets) do corpus, convertendo as palavras para minúsculas e removendo stopwords e tokens que não tenham letras nem números."""

nltk.download('punkt_tab')
sentencas = []
for tweet in tweets:
  tokens = nltk.word_tokenize(tweet)
  processada = [w.lower() for w in tokens if not w in stopwords and w.isalnum()]
  sentencas.append(processada)
len(sentencas)

sentencas[2]

"""# Gerando Word Embeddings"""

from gensim.models import Word2Vec
meu_modelo = Word2Vec(sentencas,
                      min_count=3,
                      vector_size=300,
                      workers=2,
                      window=5,
                      epochs=30)

len(meu_modelo.wv.index_to_key)

print(meu_modelo.wv.key_to_index)

"""Nessas novas WEs, as palavras mais similares à escola são:"""

meu_modelo.wv.most_similar("escola")

"""# Salvando as Word Embeddings geradas

Por fim, podemos salvar o modelo treinado para ser carregado para uso futuro (de modo similar ao que fizemos na parte 1 desse código). É importante salvar o modelo.
"""

meu_modelo.wv.save_word2vec_format("meu_modelo.bin", binary=True)

"""# Visualizando as word Embeddings

Uma das coisas mais legais de se fazer com as WEs é plotar em duas dimensões e analisar visualmente a distância entre as palavras.
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np

# %matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('classic')
from sklearn.decomposition import PCA

def display_pca_scatterplot(model, words):
  word_vectors = np.array([model[w] for w in words])

  twodim = PCA().fit_transform(word_vectors)[:, :2]

  plt.figure(figsize=(6, 6))
  plt.scatter(twodim[:,0], twodim[:,1], edgecolors='k', c='r')
  for word, (x, y) in zip(words, twodim):
    plt.text(x+0.05, y+0.05, word)

meu_modelo.wv.most_similar('escola')

"""Plotando o vetor da palavra "escola" e as 10 palavras mais próximas a ele, de acordo com o modelo que acabamos de treinar."""

words = ['escola', 'faculdade', 'facul', 'aula', 'sala', 'colégio', 'academia', 'casa', 'escolinha', 'uni', 'cursinho']
display_pca_scatterplot(meu_modelo.wv, words)

nilc_glove.most_similar('escola')

words = ['escola', 'alunos', 'escolas', 'ensino', 'colégio', 'faculdade', 'aula', 'aulas', 'educação', 'professores', 'escolar']
display_pca_scatterplot(nilc_glove, words)

